name: AWS NIXL Validation

on:
  push:
    branches:
    - main
    - "pull-request/[0-9]+"

jobs:
  run_aws_tests:
    name: Run AWS Tests
    environment: SWX_AWS
    runs-on: ubuntu-24.04
    env:
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # tmp workaround: pin UCX ver to 1.18 until EFA support is available in UCX 1.19.
      UCX_VERSION: v1.18.0
      KUBECTL_VERSION: v1.35.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup
        run: |
          set -exE
          sudo apt-get -qq update
          sudo apt-get -qq install -y curl gettext git gzip jq tar unzip

          # Install kubectl
          curl --retry 5 --retry-delay 2 --retry-all-errors -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

          # Install AWS CLI
          curl --retry 5 --retry-delay 2 --retry-all-errors "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -qq awscliv2.zip
          sudo ./aws/install --update

          # Verify AWS credentials
          aws sts get-caller-identity >/dev/null

      - name: Prepare test environment
        working-directory: ./contrib/aws-efa
        env:
          NIXL_AWS_ACCESS_KEY_ID: ${{ secrets.NIXL_AWS_ACCESS_KEY_ID }}
          NIXL_AWS_SECRET_ACCESS_KEY: ${{ secrets.NIXL_AWS_SECRET_ACCESS_KEY }}
        run: |
          ./s3_prepare.sh

      - name: Run AWS tests
        working-directory: ./contrib/aws-efa
        timeout-minutes: 180
        env:
          TEST_TIMEOUT: 60
        run: |
          set -o pipefail
          ./aws_test.sh 2>&1 | tee test_output.log

      - name: Cleanup AWS resources
        if: always()
        working-directory: ./contrib/aws-efa
        run: |
          JOB_ID=$(grep 'JOB_ID=' test_output.log | head -n1 | cut -d= -f2)
          echo "JOB_ID=$JOB_ID"
          aws batch terminate-job \
            --job-id "$JOB_ID" \
            --reason 'Terminated by GitHub Actions' || true

      - name: Cleanup test environment
        if: always()
        working-directory: ./contrib/aws-efa
        env:
          NIXL_AWS_ACCESS_KEY_ID: ${{ secrets.NIXL_AWS_ACCESS_KEY_ID }}
          NIXL_AWS_SECRET_ACCESS_KEY: ${{ secrets.NIXL_AWS_SECRET_ACCESS_KEY }}
        run: |
          ./s3_cleanup.sh
